### ISSUE TITLE
Consider using ISO 639 language strings

### ISSUE THREAD

**Issue by franz-josef-kaiser** [tvb/reCAPTCHA#12]
As you are [already using something close](https://github.com/tvb/reCAPTCHA/blob/master/views/settings.php#L27), I suggest using the full/correct ISO 639-1/2 strings. You can [include them from this repo](https://github.com/wecodemore/ISO_639-2) or fetch them via one of the GitHub CDNs (like rawgit, etc).

**Comment by tvb** [comment]
Hi I understand why you would suggest this but I have followed Google's Language code information page. (https://developers.google.com/recaptcha/docs/language) and it seems they only support a select number of languages.

**Comment by franz-josef-kaiser** [comment]
> I understand why you would suggest this but I have followed Google's Language code

Google ... oh. my. god. Thanks for the pointer.
