### ISSUE TITLE
Italian transation

### ISSUE THREAD

**Issue by Dakoom** [tvb/reCAPTCHA#13]
This is just a simple italian translation for the plugin for esoTalk:

$definitions["Are you human?"] = "Sei un umano?";
$definitions["Secret Key"] = "Chiave Segreta";
$definitions["Site Key"] = "Chiave Sito";
$definitions["Language"] = "Linguaggio";
$definitions["message.reCAPTCHA.settings"] = "Inserisci le tue chiavi reCAPTCHA (<a href='https://www.google.com/recaptcha/admin#whyrecaptcha' target='_blank'>Non hai nessuna chiave? Ottienile qui!</a>)";
$definitions["message.invalidCAPTCHA"] = "Il CAPTCHA &egrave; invalido, per favore ritenta.";

**Comment by tvb** [comment]
Thanks, but I am not going to include other languages in the repo itself.
