### ISSUE TITLE
Enable Newer Version of reCAPTCHA

### ISSUE THREAD

**Issue by daviddarnes** [tvb/reCAPTCHA#3]
Any plans to switch this to the latest version of reCAPTCHA? I'm not familiar with it so it might be something I need to change in my account. If you're unsure what I'm referring to checkout [this page on it](https://www.google.com/recaptcha/intro/index.html).

**Comment by fcpwiz** [comment]
Yes! I need this!!

**Comment by tvb** [comment]
Hi @daviddarnes and @fcpwiz Yeah sure, please go ahead and submit a pull request. I would be happy to merge it back in.

**Comment by daviddarnes** [comment]
Oh, well I'm not a PHP expert so I wouldn't know where to start. I also don't know how to switch it over to the new reCAPTCHA system :confounded: sorry.

**Comment by tvb** [comment]
Ok, I will look into it asap.

**Comment by daviddarnes** [comment]
Thanks @tvb! No rush though, I appreciate any help :smile:

**Comment by fcpwiz** [comment]
@tvb Here is a guide: https://developers.google.com/recaptcha/intro

**Comment by engleek** [comment]
Hi guys,

I've been looking into this for a couple of days. Started coding, but not sure when I'll have time to finish.

Google has PHP examples of using the new system: https://github.com/google/ReCAPTCHA/tree/master/php
It's pretty simple. The verification requests are the same as far as I can see.

First step is to update the library, and I've just submitted a pull request to that effect.

**Comment by tvb** [comment]
I've pulled in your request @engleek but I get errors. Have to look into it more.
```html
Fatal error: Call to undefined function recaptcha_get_html() in ../addons/plugins/reCAPTCHA/plugin.php on line 72
```

**Comment by tvb** [comment]
Ok, made the changes. @engleek @fcpwiz @daviddarnes can you test it and let me know your findings.
I have not made any changes to the translation part. Will do when I have more time.

**Comment by tvb** [comment]
Entry from my error log, seems there is still an issue with the code:

```html
[Thu Feb 12 10:45:51.977603 2015] [:error] [pid 12502] [client 195.154.52.102:56413] PHP Notice:  Undefined index: g-recaptcha-response in /var/www/zevenbuurtje/addons/plugins/reCAPTCHA/plugin.php on line 80, referer: .../user/join?return=%2Fuser%2Fjoin%3Freturn%3D%252Fuser%252Flogin%253Freturn%253Dconversation%252Fstart
```

**Comment by tvb** [comment]
Ok, fixed the `Undefined index: g-recaptcha-response` error. Now 3 there are new ones ;)

```
[Thu Feb 12 14:03:14.241794 2015] [:error] [pid 12989] [client x.x.x.x:62251] PHP Notice:  Use of undefined constant error - assumed 'error' in /var/www/domain.com/addons/plugins/reCAPTCHA/lib/recaptchalib.php on line 133, referer: https://www.domain.com.nl/user/join?return=%2Fuser%2Fjoin%3Freturn%3D%252Fuser%252Flogin%253Freturn%253Dconversation%252Fstart
[Thu Feb 12 14:03:14.241832 2015] [:error] [pid 12989] [client x.x.x.x:62251] PHP Notice:  Use of undefined constant codes - assumed 'codes' in /var/www/domain.com/addons/plugins/reCAPTCHA/lib/recaptchalib.php on line 133, referer: https://www.domain.com.nl/user/join?return=%2Fuser%2Fjoin%3Freturn%3D%252Fuser%252Flogin%253Freturn%253Dconversation%252Fstart
[Thu Feb 12 14:03:14.241842 2015] [:error] [pid 12989] [client x.x.x.x:62251] PHP Notice:  Undefined offset: 0 in /var/www/domain.com/addons/plugins/reCAPTCHA/lib/recaptchalib.php on line 133, referer: https://www.domain.com.nl/user/join?return=%2Fuser%2Fjoin%3Freturn%3D%252Fuser%252Flogin%253Freturn%253Dconversation%252Fstart
```

**Comment by engleek** [comment]
Weird. Are they fatal?
It looks like it comes directly from recaptchalib.php. Is that a typo on line 133, or some recent new feature?

**Comment by tvb** [comment]
Nope, they are not fatal. Just spamming my logs :cry: Will look into it later, can you test the latest commit?

**Comment by engleek** [comment]
To me it should be
```php
$recaptchaResponse->errorCodes = $answers ['errorCodes'];
```
not
```php
$recaptchaResponse->errorCodes = $answers [error-codes];
```

**Comment by tvb** [comment]
Yeah, I just figured the same. Lets try.

**Comment by tvb** [comment]
Jep! Thats seems to be it. Weird stuff from Google.

**Comment by engleek** [comment]
Thought it was a PHP 7 feature, but I can't find the reference.
In any case it's all working over here, animations and everything.
Maybe now the bots will leave us alone.

Cheers all around! :beers:

**Comment by tvb** [comment]
Yeah, just the translating is missing.

**Comment by engleek** [comment]
Hm. Seems like using the native reCAPTCHA would be easiest.
We would need to fill in the language code in the script request.

Maybe a correspondance between the forum language and these codes https://developers.google.com/recaptcha/docs/language

**Comment by tvb** [comment]
Yes, but I had trouble getting that to work. Btw check out all the pull-requests (https://github.com/google/ReCAPTCHA/pulls) for various fixes, including ours. @Google seems to be unwilling to merge.

**Comment by engleek** [comment]
Ouch…

**Comment by tvb** [comment]
Yeah.. does the plugin work for you?

**Comment by engleek** [comment]
Seems to be, yep!

**Comment by tvb** [comment]
@engleek nice. now if you can fix the translation issue we are all happy ;)

**Comment by fcpwiz** [comment]
Great work @tvb @engleek! Does this work with 1.0.0g5?

**Comment by tvb** [comment]
@fcpwiz I believe so.

**Comment by daviddarnes** [comment]
Can confirm, all working. Thanks for the update!
