### ISSUE TITLE
Latest reCAPTCHA needs work on translation

### ISSUE THREAD

**Issue by tvb** [tvb/reCAPTCHA#5]

**Comment by fcpwiz** [comment]
@tvb What is translation? I'm willing to work on it if it's easy enough.

**Comment by tvb** [comment]
So, the new reCAPTCHA version has a build in translation system. (https://github.com/tvb/reCAPTCHA/blob/master/plugin.php#L68) via https://developers.google.com/recaptcha/docs/language but I did not get it work. Might be missing something but had not time to look into it more.

**Comment by tvb** [comment]
Actually, it does work now.. hmmm.

**Comment by tvb** [comment]
I will update the plugin tonight!

**Comment by fcpwiz** [comment]
Great! Just wondering, is this correct? My first try haha

https://drive.google.com/file/d/0BwBrsjU0SiwNTFR6bFp3eklfVFE/view?usp=sharing

**Comment by tvb** [comment]
No. Give me a few min.

**Comment by fcpwiz** [comment]
Ok. Haha I thought it was wrong.

**Comment by tvb** [comment]
Fixed in https://github.com/tvb/reCAPTCHA/releases/tag/v1.2.3
