### ISSUE TITLE
Add new screenshots with updated reCAPTCHA version and settings

### ISSUE THREAD

**Issue by tvb** [tvb/reCAPTCHA#8]

**Comment by fcpwiz** [comment]
Hey, in the settings it displays: message.reCAPTCHA.settings

here is a pic: http://s29.postimg.org/vt4rpevef/Screen_Shot_2015_02_12_at_10_39_24_AM.png

**Comment by tvb** [comment]
hmmm, I know why. Hold on.

**Comment by fcpwiz** [comment]
It also doesn't display where you can get your keys anymore.

**Comment by tvb** [comment]
same issue.

**Comment by fcpwiz** [comment]
Ah ok

**Comment by tvb** [comment]
Try https://github.com/tvb/reCAPTCHA/releases/tag/v1.2.4

**Comment by fcpwiz** [comment]
Cool. I probably just being picky, but I think the "Enter your reCAPTCHA Keys (Don't have any keys yet? Get them here!)" should either go below both keys, or above both. Not in between them.

**Comment by tvb** [comment]
You are right, now there you can submit a pull-request for me :wink:

**Comment by fcpwiz** [comment]
Haha ok!

**Comment by fcpwiz** [comment]
Ahh I don't know how to move that message.reCAPTCHA.settings!

**Comment by tvb** [comment]
Its here :lollipop: https://github.com/tvb/reCAPTCHA/blob/master/views/settings.php#L17

**Comment by fcpwiz** [comment]
Oh! I was looking in plugin.php! Sorry! I'll fix it now

**Comment by tvb** [comment]
Nah, the raw php and html are mostly separated.

**Comment by fcpwiz** [comment]
BOOM

**Comment by fcpwiz** [comment]
Also, on the settings I think the "English (US)" language should be the default. Not Arabic. Haha

**Comment by tvb** [comment]
Oh, I forgot. Time for your second pull-request!

**Comment by fcpwiz** [comment]
Haha! I'll get to work!

**Comment by tvb** [comment]
This one is a more tricky one ;) Let's see if you can figure it out. You can check out my other plugins for examples.

**Comment by fcpwiz** [comment]
Huh. I can't find any other of your plugins that use a dropdown.

**Comment by tvb** [comment]
Don't give up already! Let me give you a hint: http://esotalk.org/docs/forms

**Comment by fcpwiz** [comment]
Haha! How about this: $form->setValue("Language", "English (US)");

**Comment by tvb** [comment]
Yes, thats a start. Now test that line while setting it to dutch and see if it still works..

**Comment by fcpwiz** [comment]
Damn it: http://s11.postimg.org/rzmxpd2k3/Screen_Shot_2015_02_12_at_12_38_06_PM.png

**Comment by tvb** [comment]
Ok, next hint. Look at my other plugin here https://github.com/tvb/Backup/blob/master/BackupAdminController.class.php it might help you.

**Comment by fcpwiz** [comment]
This? https://github.com/tvb/Backup/blob/master/BackupAdminController.class.php#L87-L96

**Comment by tvb** [comment]
Noo, it's way easier. Read the code and look better!

**Comment by fcpwiz** [comment]
hmm this? https://github.com/tvb/Backup/blob/master/BackupAdminController.class.php#L33-L34

**Comment by tvb** [comment]
No, thats the section (e.g. the "description") of the value. But, getting warmer.

**Comment by fcpwiz** [comment]
Aha! Is this it: https://github.com/tvb/Backup/blob/master/BackupAdminController.class.php#L62-L63

**Comment by tvb** [comment]
Good find!

```
$form->setValue("charset", C("plugin.Backup.charset", "latin1"));
```

explained: setting value of "charset" from `C("plugin.Backup.charset"` or if that is not set, set it with `latin1`

**Comment by fcpwiz** [comment]
Yay! But what does charset mean?

**Comment by tvb** [comment]
charset its the identifier for a database character set value. Not really important here.

**Comment by fcpwiz** [comment]
So

$form->setValue("charset", C("plugin.reCAPTCHA.charset", "English (US)"));

?

**Comment by tvb** [comment]
No. forget about charset. Look at what the identifier is called here https://github.com/tvb/reCAPTCHA/blob/master/views/settings.php#L27

**Comment by fcpwiz** [comment]
Array?

**Comment by tvb** [comment]
Ok, I'll help you. The identifier for this form is `language`. Now, the value for the form is not `English (US)`

**Comment by fcpwiz** [comment]
Ok. How's this: $form->setValue("language", C("plugin.reCAPTCHA.language", "en"));

**Comment by fcpwiz** [comment]
Is that correct?

**Comment by tvb** [comment]
Bingo! Go test it :sweat_smile:

**Comment by fcpwiz** [comment]
Awesome! I've tried a bunch of ways, but I don't know where to put it.

**Comment by tvb** [comment]
Just where the original setting is https://github.com/tvb/reCAPTCHA/blob/master/plugin.php#L103

**Comment by fcpwiz** [comment]
Ah! Ok.

**Comment by fcpwiz** [comment]
Ok! I just added a pull request! https://github.com/tvb/reCAPTCHA/pull/10

**Comment by tvb** [comment]
Thanks!

**Comment by fcpwiz** [comment]
Yo, when are you releasing the 1.2.5?

**Comment by tvb** [comment]
Grab it here https://github.com/tvb/reCAPTCHA/releases/tag/v1.2.5 the screenshots will follow later on.

**Comment by fcpwiz** [comment]
Hey, when are you updating the screenshots?

**Comment by tvb** [comment]
Pushed out v1.3 with the updated recaptcha library and added new screenshots.
